apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    uid: grafana-postgresql-datasource
    access: proxy
    url: database:5432
    database: joomla_db
    user: joomlauser
    secureJsonData:
      password: joomlapassword
    jsonData:
      sslmode: "disable"
      postgresVersion: 1300
    isDefault: true